### ISSUE TITLE
Little confused on how to get this to work locally

### ISSUE THREAD

**Issue by dgassman3** [MastaCoder/mySpotify#1]
I think I may be misunderstanding what address to use for the last line in the config.php file. Want to run this locally.. suggestions? Localhost does not work for me

**Comment by dgassman3** [comment]
Looks like I have everything set up but the vendor autoload piece... i get this error:

Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\models\SpotifyStats.php on line 3

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\models\SpotifyStats.php on line 3

**Comment by dgassman3** [comment]
Added an autoload script, but now getting this:

Uncaught Error: Class 'SpotifyWebAPI\Session' not found in C:\xampp\htdocs\SpotifyStats.php:5 Stack trace: #0 {main} thrown in C:\xampp\htdocs\SpotifyStats.php on line 5

**Comment by MastaCoder** [comment]
Sorry for the late response, on vacation at the moment.

The requirement of the redirect value in configuration is where Spotify will redirect once the user logs in and the auth token is sent back to the website. So if I click on the login button, I'll be redirected to Spotify's login page. This will then redirect me back to the auth page, which by default is **http://localhost**/auth.php. You only need to provide the base root of the website, the auth.php trailing is added by the script.

Seems like your Composer didn't install the MySQL library properly? Is the vendor folder located inside of the website direction with the Spotify dependencies? This can be installed by using Composer and running the following command in the root of the website. (`composer require jwilsson/spotify-web-api-php`)

**Comment by Steven-FJX** [comment]
This still doesn't help solve the original issue? I am having the same problem trying locally host. I get the following error

>  Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\mySpotify-master\mySpotify-master\models\SpotifyStats.php on line 5

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\mySpotify-master\mySpotify-master\models\SpotifyStats.php on line 5

**Comment by MastaCoder** [comment]
@Steven-FJX Hi, did you run the composer install command? You can install composer at https://getcomposer.org/, then open up CMD in the root of the folder where mySpotify is and run the command `composer require jwilsson/spotify-web-api-php`. This should make the required files to load.

Let me know if you have any other questions!
