### ISSUE TITLE
Auth Loop

### ISSUE THREAD

**Issue by mikedevvv** [MastaCoder/mySpotify#3]
I'm trying to run this on **localhost.** I have installed composer and have **run the command where the other files are located**, I have also updated the configuration.php file to have the correct details. My spotify application has the correct redirect uri set too.

However, when I try to link my spotify, it redirects me back to index.php with a **newly generated access token** but no access to the dashboard. Here's an image probably better explaining what I mean: 

![Annotation 2020-04-26 171156](https://user-images.githubusercontent.com/62149734/80313211-6760a600-87e1-11ea-858a-f8ccc2ea7378.png)

and here is what happens when I set `"**value**" = **true**` inside SpotifyStats.php:

![image](https://user-images.githubusercontent.com/62149734/80313171-308a9000-87e1-11ea-88e5-18618df78390.png)

Any support is much appreciated!

Many thanks,

Michael

**Comment by MastaCoder** [comment]
Hey Michael, try adding auth.php to the end of your confiuration file. It seems like your Spotify identification is returning to the homepage instead of the authentication page ^^

eg. If your configuration.php file contains `http://localhost/mySpotify/`, try changing that to `http://localhost/mySpotify/auth.php`.

Let me know if it works :)

**Comment by mikedevvv** [comment]
Thanks, it works now!

**Comment by mikedevvv** [comment]
as a side note, you could change 
` try {
        $userProfile = $Spotify_API->me(); // Get user from token.
        // Update user information.
        $User = [
            "valid" => true,
            "username" => $userProfile->**id**
        ];
    }`

to: 

` try {
        $userProfile = $Spotify_API->me(); // Get user from token.
        // Update user information.
        $User = [
            "valid" => true,
            "username" => $userProfile->**display_name**
        ];
    }`

inside the SpotifyStats.php file.

It just looks nicer than the id :)

Many thanks,

Michael

**Comment by MastaCoder** [comment]
I'll definitely consider thanks! If you want you can send a pull request and I can merge it too :)
